# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/se_ml_stock_and_curriencies',
                'doc_host': 'https://wojciech11.github.io',
                'git_url': 'https://github.com/wojciech11/se_ml_stock_and_curriencies',
                'lib_path': 'se_ml_stock_and_curriencies'},
  'syms': { 'se_ml_stock_and_curriencies.core': { 'se_ml_stock_and_curriencies.core.foo': ( 'core.html#foo',
                                                                                            'se_ml_stock_and_curriencies/core.py')}}}
